name: Download S3 Artifact
description: 'Download an artifact from S3'
inputs:
  bucket:
    description: 'S3 bucket'
    required: true
  filename:
    description: 'Target directory'
    required: true
  aws_region:
    description: 'S3 region'
    required: true
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  context:
    description: 'Unzip target directory'
    default: .
    required: false
runs:
  using: composite
  steps:
    -
      name: Download from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_region: ${{ inputs.aws_region }}
        source: s3://${{ inputs.bucket }}/${{ github.repository }}/${{ inputs.filename }}.zip
        destination: ${{ inputs.context }}/${{ inputs.filename }}.zip
    -
      name: Unzip
      uses: montudor/action-unzip@v1
      with:
        args: unzip -qq ${{ inputs.context }}/${{ inputs.filename }}.zip -d ${{ inputs.context }}/${{ inputs.filename }}
